version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docker"
    schedule:
      interval: "daily"
